"""added date and starttime and end time to sessions models)


Revision ID: 1cbcb050619c
Revises: e5bd9c8a189c
Create Date: 2023-08-20 13:02:14.767623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cbcb050619c'
down_revision = 'e5bd9c8a189c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('start_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.Time(), nullable=True))
        batch_op.drop_column('date_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_time', sa.DATETIME(), nullable=True))
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
