"""added session type columns on uvers

Revision ID: 2a6de4599af7
Revises: 913e37f2813a
Create Date: 2023-08-28 15:30:31.049242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a6de4599af7'
down_revision = '913e37f2813a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('available_in_person', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('available_virtual', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('available_coaching', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('available_coaching')
        batch_op.drop_column('available_virtual')
        batch_op.drop_column('available_in_person')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
