"""added boolean to user class

Revision ID: 913e37f2813a
Revises: b304fcb4c855
Create Date: 2023-08-28 15:15:45.018476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '913e37f2813a'
down_revision = 'b304fcb4c855'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_available_as_reader', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_available_as_reader')

    # ### end Alembic commands ###
