"""added availability table

Revision ID: b304fcb4c855
Revises: a44fa29044f1
Create Date: 2023-08-28 15:00:28.274168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b304fcb4c855'
down_revision = 'a44fa29044f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_availabilities_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('availability_days', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('availability_start_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('availability_end_time', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('availability_end_time')
        batch_op.drop_column('availability_start_time')
        batch_op.drop_column('availability_days')

    op.drop_table('availabilities')
    # ### end Alembic commands ###
