"""switched columns in availabilities to strings

Revision ID: c0fb0a891655
Revises: 2a6de4599af7
Create Date: 2023-08-28 19:11:06.198435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0fb0a891655'
down_revision = '2a6de4599af7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('availabilities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_of_week', sa.String(), nullable=True))
        batch_op.alter_column('start_time',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               nullable=True)
        batch_op.alter_column('end_time',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('availabilities', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('start_time',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('day_of_week')

    # ### end Alembic commands ###
