"""removed user avail columns

Revision ID: e3b9f6a88009
Revises: c0fb0a891655
Create Date: 2023-08-28 19:15:01.151330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3b9f6a88009'
down_revision = 'c0fb0a891655'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('availability_end_time')
        batch_op.drop_column('availability_start_time')
        batch_op.drop_column('availability_days')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('availability_days', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('availability_start_time', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('availability_end_time', sa.TIME(), nullable=True))

    # ### end Alembic commands ###
